---
title: ❗ERROR - git blog ArgumentError
author: ggggraceful
date: 2023-01-24
categories: [02.ERROR]
tags: [error]
---

```
> Run bash tools/test
Configuration file: /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/_config.yml
 Theme Config file: /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/_config.yml
            Source: /home/runner/work/ggggraceful.github.io/ggggraceful.github.io
       Destination: /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/_sitebaseurl: ''
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 2.885 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
htmlproofer 3.19.4 | Error:  _site does not exist
/home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/gems/html-proofer-3.19.4/lib/html-proofer.rb:25:in `check_file': _site does not exist (ArgumentError)

    raise ArgumentError, "#{file} does not exist" unless File.exist?(file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/gems/html-proofer-3.19.4/bin/htmlproofer:114:in `block (2 levels) in <top (required)>'
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/gems/html-proofer-3.19.4/bin/htmlproofer:11:in `<top (required)>'
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/bin/htmlproofer:25:in `load'
	from /home/runner/work/ggggraceful.github.io/ggggraceful.github.io/vendor/bundle/ruby/3.2.0/bin/htmlproofer:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.1/libexec/bundle:45:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.1/libexec/bundle:33:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle:25:in `<main>'
Error: The operation was canceled.
```
